# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 07:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0027_auto_20160405_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 7, 21, 51, 985414)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 7, 21, 51, 986545)),
        ),
    ]
