# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 11:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0029_auto_20160406_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 11, 31, 17, 542559)),
        ),
    ]
