# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-06 11:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django_counter_field.fields
import django_model_changes.changes


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0030_auto_20160406_1131'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=500)),
                ('date', models.DateTimeField(default=datetime.datetime(2016, 4, 6, 11, 34, 47, 916353))),
            ],
            bases=(django_model_changes.changes.ChangesMixin, models.Model),
        ),
        migrations.AddField(
            model_name='article',
            name='comment_count',
            field=django_counter_field.fields.CounterField(default=0),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 6, 11, 34, 47, 915032)),
        ),
        migrations.AddField(
            model_name='comment',
            name='Article_comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.Article'),
        ),
        migrations.AddField(
            model_name='emotion',
            name='Comment_emotion_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='like',
            name='Comment_like_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.Comment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mark',
            name='Article_mark_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='DjangoApp.Comment'),
            preserve_default=False,
        ),
    ]
