# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-08 14:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django_counter_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0033_auto_20160408_1427'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='user_id',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='Article_Tag_id',
        ),
        migrations.RemoveField(
            model_name='tag',
            name='word',
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(to='DjangoApp.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='veiw_count',
            field=django_counter_field.fields.CounterField(default=0),
        ),
        migrations.AddField(
            model_name='tag',
            name='tag_title',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 14, 36, 0, 136914)),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_denied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='article',
            name='is_publish',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 8, 14, 36, 0, 141404)),
        ),
    ]
