# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 16:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0045_auto_20160409_1629'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='lock',
            new_name='is_lock',
        ),
        migrations.AddField(
            model_name='site',
            name='Name',
            field=models.CharField(default=b'Blog System', max_length=100),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 16, 36, 25, 578291)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 16, 36, 25, 580806)),
        ),
    ]
