# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-09 17:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0046_auto_20160409_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='site',
            new_name='LockSystem',
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 17, 45, 12, 830511)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 9, 17, 45, 12, 832972)),
        ),
    ]
