# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 10:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0054_auto_20160410_1006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 10, 7, 28, 936963)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 10, 7, 28, 943339)),
        ),
    ]
