# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 15:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0057_auto_20160410_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 15, 37, 52, 89269)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 15, 37, 52, 91294)),
        ),
    ]
