# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-10 16:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoApp', '0058_auto_20160410_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 16, 10, 31, 963033)),
        ),
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2016, 4, 10, 16, 10, 31, 965844)),
        ),
    ]
